import Link from "next/link";
import { db } from "@/lib/db";
import { IngestButton } from "@/components/IngestButton";

const money = (value: unknown) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(Number(value || 0));
export default async function DashboardPage() {
  const [intents, contacts, companies] = await Promise.all([db.expressionOfIntent.aggregate({ _sum: { estimatedValue: true }, where: { confirmedAt: { not: null } } }), db.contact.groupBy({ by: ["callStatus"], _count: { _all: true } }), db.targetCompany.findMany({ where: { contacts: { some: { callStatus: "not_contacted", verified: true } } }, orderBy: { priorityScore: "desc" }, take: 10 })]);
  const committed = Number(intents._sum.estimatedValue || 0), target = 75000, progress = Math.min(100, committed / target * 100);
  return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Weekly review</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Build today’s conversations.</h1><p className="mt-2 text-sm text-slate-600">Fresh award signals, ranked targets and a clear route to £75k.</p></div><IngestButton /></div><section className="grid gap-4 md:grid-cols-3"><div className="card p-5 md:col-span-2"><div className="flex justify-between"><div><p className="eyebrow">Confirmed annual intent</p><p className="mt-2 text-3xl font-bold">{money(committed)}</p></div><span className="text-sm font-medium text-slate-500">{Math.round(progress)}% of £75k</span></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-sm text-slate-500">{money(Math.max(0, target - committed))} remaining to founder validation target.</p></div><div className="card p-5"><p className="eyebrow">Next action</p><p className="mt-2 text-lg font-semibold">Call the highest-pain bidder</p><Link className="mt-4 inline-block text-sm font-semibold text-emerald-700 hover:underline" href="/call-sheet">Open call sheet →</Link></div></section><section className="grid gap-4 lg:grid-cols-3"><div className="card p-5"><p className="eyebrow">Contact pipeline</p><div className="mt-4 space-y-3">{["not_contacted", "called", "callback", "hot", "dead", "intent_signed"].map((status) => <div key={status} className="flex items-center justify-between text-sm"><span className="capitalize text-slate-600">{status.replace("_", " ")}</span><strong>{contacts.find((item) => item.callStatus === status)?._count._all || 0}</strong></div>)}</div></div><div className="card p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><p className="eyebrow">Top uncontacted companies</p><h2 className="mt-1 text-lg font-semibold">Your highest-priority research targets</h2></div><Link href="/companies" className="text-sm font-semibold text-emerald-700">View all</Link></div><div className="mt-4 divide-y divide-slate-100">{companies.length ? companies.map((company) => <Link href={`/companies/${company.id}`} key={company.id} className="flex items-center justify-between py-3 hover:bg-slate-50"><div><p className="font-medium">{company.companyName}</p><p className="text-xs text-slate-500">{company.lastBidBuyer || "No matched award yet"}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-sm font-bold text-emerald-700">{Number(company.priorityScore || 0).toFixed(1)}</span></Link>) : <p className="py-6 text-sm text-slate-500">Add a company and verified contact, then refresh award data to create a ranked list.</p>}</div></div></section></div>;
}
